subTypeTable<-read.delim(file = "~/Research/CirSeq/ResSubTable_Pechmann2014.txt" , head = T)
rownames(subTypeTable)<-colnames(subTypeTable)
states=as.array(c('TTT', 'TTC', 'TTA', 'TTG',
                  'TCT', 'TCC', 'TCA', 'TCG',
                  'TAT', 'TAC', 'TAA', 'TAG',
                  'TGT', 'TGC', 'TGA', 'TGG',
                  'CTT', 'CTC', 'CTA', 'CTG',
                  'CCT', 'CCC', 'CCA', 'CCG',
                  'CAT', 'CAC', 'CAA', 'CAG',
                  'CGT', 'CGC', 'CGA', 'CGG',
                  'ATT', 'ATC', 'ATA', 'ATG',
                  'ACT', 'ACC', 'ACA', 'ACG',
                  'AAT', 'AAC', 'AAA', 'AAG',
                  'AGT', 'AGC', 'AGA', 'AGG',
                  'GTT', 'GTC', 'GTA', 'GTG',
                  'GCT', 'GCC', 'GCA', 'GCG',
                  'GAT', 'GAC', 'GAA', 'GAG',
                  'GGT', 'GGC', 'GGA', 'GGG', NA))

alphaVec<-c("A","C","D","E","F","G","H","I","K","L","M","N","P","Q","R","S","T","V","W","Y","X","U")

residues = c( "F","F","L","L",
              "S","S","S","S",
              "Y","Y","X","X",
              "C","C","X","W",
              "L","L","L","L",
              "P","P","P","P",
              "H","H","Q","Q",
              "R","R","R","R",
              "I","I","I","M",
              "T","T","T","T",
              "N","N","K","K",
              "S","S","R","R",
              "V","V","V","V",
              "A","A","A","A",
              "D","D","E","E",
              "G","G","G","G", "U")

res3 = c( "PHE","PHE","LEU","LEU",
          "SER","SER","SER","SER",
          "TYR","TYR","XXX","XXX",
          "CYS","CYS","XXX","TRP",
          "LEU","LEU","LEU","LEU",
          "PRO","PRO","PRO","PRO",
          "HIS","HIS","GLN","GLN",
          "ARG","ARG","ARG","ARG",
          "ILE","ILE","ILE","MET",
          "THR","THR","THR","THR",
          "ASN","ASN","LYS","LYS",
          "SER","SER","ARG","ARG",
          "VAL","VAL","VAL","VAL",
          "ALA","ALA","ALA","ALA",
          "ASP","ASP","GLU","GLU",
          "GLY","GLY","GLY","GLY", "UTR")
